mindmap
    root(tcp的连接与关闭)
    ::icon(fa fa-book)
        1.网络异常且有数据传输
            1.1 超时重传 + 确认机制
        2.异常无数据传输
            2.1 开启keep-alive
            2.2 关闭keep-alive
        3.异常关闭
        4.正常无数据传输
            4.1 开启keep-alive
            4.2 关闭keep-alive
        5.主动关闭
        6.异常关闭后再回复


