sequenceDiagram
    商户 -->> 支付中台:下单请求
    支付中台 -->> 三方通道:下单请求
    三方通道 ->> 支付中台: 返回支付链接
    支付中台 ->> 商户:返回支付链接
    create actor user
    商户-->>user:支付链接
    user->> 三方通道:完成支付
    三方通道 ->> 支付中台:支付结果
    支付中台 ->> 商户:通知结果
    商户 -->> user:发货




    ---
title: git rebase
---
flowchart TD
    1.创建feature分支feature1
    --> 
    2.修改主分支
    -->
    3.提交主分支
    -->
    4.修改特性分支
    -->
    5.提交特性分支
    -->
    7.切换到main分支并feature1分支
    --> 
    8.提交发生冲突